apiVersion: v1
kind: Service
metadata:
  name: sample-service
spec:
  selector:
    run: echo-client
  ports:
    - protocol: "TCP"
      port: 8080
      nodePort: 30000
  type: NodePort


---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: echo-client
  name: echo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      run: echo-client
  template:
    metadata:
      labels:
        run: echo-client
    spec:
      containers:
        - image: cdchathura/grpc-client:1.0
          name: echo-client
          env:
            - name: ECHO_SERVICE_TARGET
              value: dns:///echo-server:8080